# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/verilog_practice/project_3/project_3.srcs/sources_1/ip/line_bram_1/line_bram_1.xci
# IP: The module: 'line_bram_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/verilog_practice/project_3/project_3.gen/sources_1/ip/line_bram_1/line_bram_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'line_bram_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/verilog_practice/project_3/project_3.srcs/sources_1/ip/line_bram_1/line_bram_1.xci
# IP: The module: 'line_bram_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/verilog_practice/project_3/project_3.gen/sources_1/ip/line_bram_1/line_bram_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'line_bram_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
