# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/verilog_practice/project_line_buffer_2/project_line_buffer_2.srcs/sources_1/ip/line_fifo/line_fifo.xci
# IP: The module: 'line_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/verilog_practice/project_line_buffer_2/project_line_buffer_2.gen/sources_1/ip/line_fifo/line_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'line_fifo'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/verilog_practice/project_line_buffer_2/project_line_buffer_2.gen/sources_1/ip/line_fifo/line_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'line_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/verilog_practice/project_line_buffer_2/project_line_buffer_2.srcs/sources_1/ip/line_fifo/line_fifo.xci
# IP: The module: 'line_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/verilog_practice/project_line_buffer_2/project_line_buffer_2.gen/sources_1/ip/line_fifo/line_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'line_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/verilog_practice/project_line_buffer_2/project_line_buffer_2.gen/sources_1/ip/line_fifo/line_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'line_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
