# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/verilog_practice/project_3/project_3.srcs/sources_1/ip/buffer_RAM_12x131072/buffer_RAM_12x131072.xci
# IP: The module: 'buffer_RAM_12x131072' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/verilog_practice/project_3/project_3.gen/sources_1/ip/buffer_RAM_12x131072/buffer_RAM_12x131072_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'buffer_RAM_12x131072'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/verilog_practice/project_3/project_3.srcs/sources_1/ip/buffer_RAM_12x131072/buffer_RAM_12x131072.xci
# IP: The module: 'buffer_RAM_12x131072' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/verilog_practice/project_3/project_3.gen/sources_1/ip/buffer_RAM_12x131072/buffer_RAM_12x131072_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'buffer_RAM_12x131072'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
